@echo off
chcp 65001 > nul
md "Cursos"
cd "Cursos"
    md "1"
    cd "1"
        md "1-A"
        cd "1-A"
            echo. >listaAlumnos-1-A.md
            echo. >Materias-1-A.md
    cd ..
        md "1-B"
        cd "1-B"
            echo. >listaAlumnos-1-B.md
            echo. >Materias-1-B.md
        cd ..
        md "1-C"
        cd "1-C"
            echo. >listaAlumnos-1-C.md
            echo. >Materias-1-C.md
    cd ..
cd ..
    md "2"
    cd "2"
        md "2-A"
        cd "2-A"
            echo. >listaAlumnos-2-A.md
            echo. >Materias-2-A.md
            
    cd ..
        md "2-B"
        cd "2-B"
            echo. >listaAlumnos-2-B.md
            echo. >Materias-2-B.md
        cd ..
        md "2-C"
        cd "2-C"
            echo. >listaAlumnos-2-C.md
            echo. >Materias-2-C.md
    cd ..
cd ..
    md "3"
    cd "3"
        md "3-A"
        cd "3-A"
            echo. >listaAlumnos-3-A.md
            echo. >Materias-3-A.md
    cd ..
        md "3-B"
        cd "3-B"
            echo. >listaAlumnos-3-B.md
            echo. >Materias-3-B.md
    cd ..
cd ..
        md "4"
        cd "4"
        md "4-A"
        cd "4-A"
            echo. >listaAlumnos-4-A.md
            echo. >Materias-4-A.md
    cd ..
cd ..    
        md "5"
        cd "5"
        md "5-A"
        cd "5-A"
            echo. >listaAlumnos-5-A.md
            echo. >Materias-5-A.md
    cd ..
cd ..
        md "6"
        cd "6"
        md "6-A"
        cd "6-A"
            echo. >listaAlumnos-6-A.md
            echo. >Materias-6-A.md
    cd ..
cd ..
exit